# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:

  branches:

    include:

      - main

 

pr:

  branches:

    include:

      - '*'

 

pool:

  vmImage: 'ubuntu-latest'

 

steps:

- task: Docker@2

  displayName: 'Pull image'

  inputs:

    containerRegistry: 'nethraregistry.azurecr.io'

    repository: 'nethraregistry'

    command: 'pull'

    includeLatestTag: false

 

- task: Docker@2

  displayName: 'Push image'

  inputs:

    containerRegistry: 'shreyaregistry.azurecr.io'

    repository: 'shreyaregistry'

    command: 'push'

    includeLatestTag: false

...