apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenbuild
  template:
    metadata:
      labels:
        app: mavenbuild
    spec:
      containers:
      - name: dockercontainer23
        image: nethrashreec/mavenbuildproject:latest
        ports:
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: mavenbuild
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 31000
  type: NodePort
